# -*- coding: utf-8 -*-
"""File guide

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136px56zpdFZ908qZ8znJYQswKbnFRXhw
"""

!pip install -q \
    "numpy==2.0.2" \
    "pandas==2.2.2" \
    "scipy==1.13.1" \
    "scikit-learn==1.5.2" \
    "statsmodels==0.14.2" \
    "matplotlib" \
    "pymc" \
    "arviz"

import numpy as np, pandas as pd, matplotlib, scipy, statsmodels, sklearn
import pymc as pm, arviz as az

print("numpy       :", np.__version__)
print("pandas      :", pd.__version__)
print("scipy       :", scipy.__version__)
print("sklearn     :", sklearn.__version__)
print("statsmodels :", statsmodels.__version__)
print("pymc        :", pm.__version__)
print("arviz       :", az.__version__)

from google.colab import files

print("📂 Chọn file CSV để upload...")
uploaded = files.upload()

# Lấy tên file đầu tiên vừa upload
DATA_PATH = list(uploaded.keys())[0]
print("✅ File đã upload:", DATA_PATH)

import pandas as pd

def safe_read_csv(path: str):
    encodings_to_try = ["utf-8", "utf-8-sig", "latin1", "cp1252", "cp1258"]
    seps_to_try = [",", ";", "\t", "|"]

    for enc in encodings_to_try:
        for sep in seps_to_try:
            try:
                df = pd.read_csv(path, encoding=enc, sep=sep)
                print(f"✅ Đọc thành công với encoding={enc}, sep='{sep}'")
                print("Shape:", df.shape)
                print("Các cột:", df.columns.tolist()[:10])
                return df
            except Exception:
                continue
    raise ValueError("❌ Không đọc được file CSV với các encoding/sep phổ biến.")

df = safe_read_csv(DATA_PATH)
df.head()

import numpy as np
import pandas as pd

assert "Score" in df.columns, "❌ Không thấy cột 'Score' trong dữ liệu!"
y_raw = df["Score"]

def is_binary_series(s: pd.Series) -> bool:
    vals = pd.unique(s.dropna())
    return set(vals).issubset({0, 1})

target_is_binary = is_binary_series(y_raw)

if target_is_binary:
    print("✅ 'Score' đã nhị phân (0/1) → dùng trực tiếp.")
    y = y_raw.astype(int)
    selected_threshold = None
else:
    # Classification-oriented: quét các ngưỡng và CHỌN ngưỡng sao cho tỷ lệ lớp gần 50/50 nhất
    vals = y_raw.astype(float)
    lo, hi = vals.quantile(0.2), vals.quantile(0.8)  # tránh outlier
    candidates = np.linspace(lo, hi, 51)
    best_thr, best_balance = candidates[0], -1
    for thr in candidates:
        y_tmp = (vals >= thr).astype(int)
        balance = 1 - abs(y_tmp.mean() - 0.5)*2  # 1= cân bằng hoàn hảo, 0 = lệch hẳn
        if balance > best_balance:
            best_balance, best_thr = balance, thr

    selected_threshold = float(best_thr)
    y = (vals >= selected_threshold).astype(int)
    print("⚠️ 'Score' là liên tục.")
    print(f"👉 Chọn threshold (classification-oriented balance) = {selected_threshold:.4f} | "
          f"Class balance ≈ {y.mean():.2%} (tỷ lệ lớp 1).")

X_raw = df.drop(columns=["Score"])
print("📊 X:", X_raw.shape, " | y:", y.shape)

# Người dùng chỉ chỉnh tại đây (hoặc giữ "Khuyến nghị")
USER_MLE = {
    "penalty": "Khuyến nghị",   # "Khuyến nghị" | "none" | "l2"
    "C":       "Khuyến nghị",   # "Khuyến nghị" | số (vd 1.0, 10.0, 1e6)
    "solver":  "Khuyến nghị"    # "Khuyến nghị" | "lbfgs" | "saga"
}

# Map khuyến nghị → cấu hình phù hợp MLE
penalty = None if USER_MLE["penalty"] == "Khuyến nghị" else (None if USER_MLE["penalty"]=="none" else USER_MLE["penalty"])
C       = (1e6 if USER_MLE["C"] == "Khuyến nghị" else float(USER_MLE["C"]))  # C rất lớn ~ MLE
solver  = ("lbfgs" if USER_MLE["solver"] == "Khuyến nghị" else USER_MLE["solver"])

print("⚙️ Logistic (MLE) params →", {"penalty": penalty, "C": C, "solver": solver})

# CELL 2 — Chọn tham số MLE (có khuyến nghị & range)
# - penalty:  None (MLE, KHÁY KHUYẾN NGHỊ)  hoặc 'l2' (Ridge)
# - C:        độ “nới lỏng” regularization. C rất lớn ~ MLE. Range an toàn: 1e-2 .. 1e8 (khuyến nghị: 1e6)
# - solver:   'lbfgs' (khuyến nghị) hoặc 'saga'
# - class_weight: None hoặc 'balanced' (khuyến nghị nếu lớp lệch)
# - test_size: 0.10 .. 0.40 (khuyến nghị 0.25)
# - random_state: 42 (giữ cố định để tái lập)

from IPython.display import display, Markdown
import math

try:
    import ipywidgets as widgets

    display(Markdown(r"""
**⚙️ Tuỳ chọn tham số cho Logistic Regression (MLE)**

**Khuyến nghị (an toàn & tổng quát):**
- `penalty` = **None** *(không phạt → MLE thuần)*
- `C` = **1e6** *(rất lớn → gần MLE)*
- `solver` = **lbfgs**
- `class_weight` = **balanced** *(nên dùng nếu class lệch)*
- `test_size` = **0.25**
- `random_state` = **42**

Bạn có thể tuỳ chỉnh trong phạm vi gợi ý bên dưới.
    """))

    # Widgets
    penalty_dd = widgets.Dropdown(
        options=[("MLE (không phạt)", "none"), ("L2 (Ridge)", "l2")],
        value="none", description="penalty"
    )

    # FloatLogSlider: 1e-2 .. 1e8
    C_slider = widgets.FloatLogSlider(
        base=10.0, min=-2, max=8, step=0.1, value=1e6,
        description="C (log10)"
    )
    C_help = widgets.Label("↳ C rất lớn ~ MLE (khuyến nghị: 1e6). Phạm vi: 1e-2 → 1e8.")

    solver_dd = widgets.Dropdown(
        options=["lbfgs", "saga"],
        value="lbfgs", description="solver"
    )

    cw_dd = widgets.Dropdown(
        options=[("None", None), ("balanced", "balanced")],
        value="balanced", description="class_weight"
    )

    ts_slider = widgets.FloatSlider(
        min=0.10, max=0.40, step=0.01, value=0.25,
        readout_format=".2f", description="test_size"
    )

    rs_int = widgets.IntText(value=42, description="random_state")

    confirm_btn = widgets.Button(
        description="✅ Xác nhận tham số",
        button_style="success"
    )
    out = widgets.Output()

    def on_confirm_clicked(b):
        with out:
            out.clear_output()
            # Map 'none' → None theo sklearn
            penalty_val = None if penalty_dd.value == "none" else penalty_dd.value
            C_val = float(C_slider.value)
            solver_val = solver_dd.value
            class_weight_val = cw_dd.value
            test_size_val = float(ts_slider.value)
            random_state_val = int(rs_int.value)

            # Ràng buộc mềm (clamp)
            C_val = max(1e-2, min(C_val, 1e8))
            test_size_val = max(0.10, min(test_size_val, 0.40))

            # Lưu cấu hình dùng cho Cell 3
            global USER_MLE
            USER_MLE = {
                "penalty": penalty_val,
                "C": C_val,
                "solver": solver_val,
                "class_weight": class_weight_val,
                "test_size": test_size_val,
                "random_state": random_state_val,
            }

            print("ĐÃ CHỌN THAM SỐ MLE:")
            for k, v in USER_MLE.items():
                print(f" - {k}: {v}")
            print("\n👉 Tiếp tục chạy **Cell 3** để huấn luyện MLE theo các tham số trên.")

    confirm_btn.on_click(on_confirm_clicked)

    display(
        widgets.VBox([
            penalty_dd,
            widgets.HBox([C_slider]), C_help,
            solver_dd,
            cw_dd,
            ts_slider,
            rs_int,
            confirm_btn,
            out
        ])
    )

except Exception as _:
    # Fallback nếu ipywidgets không khả dụng → cho người dùng điền tay (vẫn có khuyến nghị)
    print("⚠️ ipywidgets chưa sẵn. Dùng cấu hình mặc định có khuyến nghị, có thể sửa số bên dưới.")
    USER_MLE = {
        "penalty": None,       # None = MLE (khuyến nghị) | hoặc 'l2'
        "C": 1e6,              # 1e-2 .. 1e8 (khuyến nghị 1e6)
        "solver": "lbfgs",     # 'lbfgs' (khuyến nghị) | 'saga'
        "class_weight": "balanced",  # None | 'balanced'
        "test_size": 0.25,     # 0.10 .. 0.40
        "random_state": 42,
    }
    print("USER_MLE =", USER_MLE)
    print("👉 Tiếp tục chạy **Cell 3** để huấn luyện MLE theo các tham số trên.")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X_raw, y, test_size=0.25, random_state=42, stratify=y
)

# Preprocess
numeric_cols = [c for c in X_raw.columns if np.issubdtype(df[c].dtype, np.number)]
categorical_cols = [c for c in X_raw.columns if c not in numeric_cols]

numeric_tf = Pipeline([("imputer", SimpleImputer(strategy="median")),
                       ("scaler", StandardScaler())])
categorical_tf = Pipeline([("imputer", SimpleImputer(strategy="most_frequent")),
                           ("onehot", OneHotEncoder(handle_unknown="ignore"))])

preprocess = ColumnTransformer([
    ("num", numeric_tf, numeric_cols),
    ("cat", categorical_tf, categorical_cols)
])

# Model (MLE ~ penalty=None hoặc C rất lớn)
clf = LogisticRegression(max_iter=1000, penalty=penalty, C=C, solver=solver)

pipe = Pipeline([("preprocess", preprocess), ("clf", clf)])
pipe.fit(X_train, y_train)

# Evaluate
y_pred = pipe.predict(X_test)
metrics = {
    "Accuracy":  accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred, zero_division=0),
    "Recall":    recall_score(y_test, y_pred, zero_division=0),
    "F1":        f1_score(y_test, y_pred, zero_division=0),
}
print("\n📊 Logistic Regression (MLE) metrics:")
for k,v in metrics.items():
    print(f"- {k}: {v:.3f}")
print("\n🔎 Confusion matrix:\n", confusion_matrix(y_test, y_pred))

# CELL 4 — Giải thích kết quả + Top 5 biến dương/âm + Kết luận

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

# 1) Tính lại các chỉ số đánh giá (phòng khi bạn chạy cell 3 độc lập)
y_pred = pipe.predict(X_test)
try:
    y_proba = pipe.predict_proba(X_test)[:, 1]
except Exception:
    y_proba = None

acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec  = recall_score(y_test, y_pred, zero_division=0)
f1   = f1_score(y_test, y_pred, zero_division=0)
cm   = confusion_matrix(y_test, y_pred)
auc  = roc_auc_score(y_test, y_proba) if y_proba is not None else None

print("📊 ĐÁNH GIÁ MÔ HÌNH (Logistic MLE)")
print(f"- Accuracy  : {acc:.3f}  → Tỷ lệ dự đoán đúng trên toàn bộ mẫu")
print(f"- Precision : {prec:.3f}  → Trong các dự đoán '1', bao nhiêu % là đúng (hạn chế false positive)")
print(f"- Recall    : {rec:.3f}  → Trong các mẫu '1' thật, bắt được bao nhiêu % (hạn chế false negative)")
print(f"- F1-score  : {f1:.3f}   → Trung hoà Precision & Recall (phù hợp khi dữ liệu lệch lớp)")
if auc is not None:
    print(f"- ROC AUC   : {auc:.3f}  → Khả năng xếp hạng xác suất đúng (cao hơn tốt hơn)")
print("\n🔎 Confusion Matrix [ [TN, FP], [FN, TP] ]:")
print(cm)

# 2) Lấy tên đặc trưng sau ColumnTransformer
preproc = pipe.named_steps["preprocess"]
clf     = pipe.named_steps["clf"]

# Tên numeric giữ nguyên, tên categorical lấy từ OneHotEncoder
num_cols = numeric_cols
ohe = preproc.named_transformers_["cat"].named_steps["onehot"]
cat_feature_names = list(ohe.get_feature_names_out(categorical_cols))
feature_names = list(num_cols) + cat_feature_names

# 3) Hệ số của Logistic (dấu dương/âm cho biết hướng ảnh hưởng)
coefs = clf.coef_.ravel()
coef_df = pd.DataFrame({"feature": feature_names, "coef": coefs})
coef_df["abs_coef"] = coef_df["coef"].abs()

# Top 5 dương & âm
top_pos = (coef_df.sort_values("coef", ascending=False)
                  .head(5)[["feature", "coef"]]
                  .reset_index(drop=True))
top_neg = (coef_df.sort_values("coef", ascending=True)
                  .head(5)[["feature", "coef"]]
                  .reset_index(drop=True))

print("\n📈 Top 5 biến ảnh hưởng DƯƠNG (coef > 0) — tăng xác suất lớp '1':")
display(top_pos)

print("\n📉 Top 5 biến ảnh hưởng ÂM (coef < 0) — giảm xác suất lớp '1':")
display(top_neg)

# 4) Kết luận ngắn gọn bằng lời
pos_list = [f"{r.feature}" for _, r in top_pos.iterrows()]
neg_list = [f"{r.feature}" for _, r in top_neg.iterrows()]

print("\n🧭 KẾT LUẬN NGẮN GỌN")
if selected_threshold is not None:
    print(f"- Target 'Score' ban đầu liên tục → đã chọn ngưỡng = {selected_threshold:.4f} (method: classification-oriented balance).")
else:
    print("- Target 'Score' đã là nhị phân, không cần chọn ngưỡng.")

print(f"- Hiệu suất tổng quan: Accuracy={acc:.3f}, Precision={prec:.3f}, Recall={rec:.3f}, F1={f1:.3f}" + (f", AUC={auc:.3f}" if auc is not None else ""))
if pos_list:
    print(f"- Biến ảnh hưởng **dương** (tăng xác suất thuộc lớp '1'): {', '.join(pos_list)}.")
if neg_list:
    print(f"- Biến ảnh hưởng **âm** (giảm xác suất thuộc lớp '1'): {', '.join(neg_list)}.")

print("\n💡 Diễn giải: Với Logistic Regression, hệ số dương nghĩa là khi biến tăng (giữ các biến khác cố định) → xác suất thuộc lớp '1' tăng; hệ số âm thì ngược lại.")

# CELL 5A — Chuẩn bị cho Bayesian Logistic Regression (PyMC)

# Yêu cầu: đã chạy Cell 1–3 (để có X_train, X_test, y_train, y_test, pipe)
import numpy as np, pandas as pd

print("Bayesian Logistic sẽ dùng dữ liệu đã tách train/test ở MLE để so sánh công bằng.")
print("Quy trình:")
print("1) Lấy ma trận đặc trưng sau tiền xử lý (giống MLE).")
print("2) Khai báo prior Gaussian cho hệ số & intercept.")
print("3) Sampling bằng NUTS (PyMC) theo thông số bạn chọn.")
print("4) Chấm điểm trên test set + top biến dương/âm + kết luận.")

# Lấy transformer đã fit trong MLE
preproc = pipe.named_steps["preprocess"]
Xt_train = preproc.transform(X_train)
Xt_test  = preproc.transform(X_test)

# Tên đặc trưng sau OneHot
ohe = preproc.named_transformers_["cat"].named_steps["onehot"]
feature_names = list(numeric_cols) + list(ohe.get_feature_names_out(categorical_cols))

Xt_train.shape, Xt_test.shape, len(feature_names)

# CELL 5B — Chọn tham số Bayesian (có khuyến nghị & range)
# Thông số có thể chỉnh:
# - prior_sigma_beta: độ lệch chuẩn của prior cho hệ số (khuyến nghị: 10.0)
# - prior_sigma_intercept: độ lệch chuẩn của prior cho intercept (khuyến nghị: 10.0)
# - draws: số mẫu posterior sau warmup (khuyến nghị: 1000; DEMO nhanh: 500)
# - tune: số mẫu warmup (khuyến nghị: 1000; DEMO nhanh: 500)
# - target_accept: 0.9 ~ 0.95 (cao hơn → an toàn hơn nhưng chậm hơn)
# - chains: 2 (khuyến nghị cho báo cáo; 1 cho demo nhanh)
# - cores: 1 (Colab ổn định)
# - random_seed: 42 (tái lập)
# - mode: "Khuyến nghị" | "Nhanh (demo)"

from IPython.display import display, Markdown

try:
    import ipywidgets as widgets

    display(Markdown(r"""
**⚙️ Tuỳ chọn thông số cho Bayesian Logistic (PyMC)**

**Khuyến nghị (chuẩn báo cáo):**
- `prior_sigma_beta` = **10.0**
- `prior_sigma_intercept` = **10.0**
- `draws` = **1000**, `tune` = **1000**
- `target_accept` = **0.90**
- `chains` = **2**, `cores` = **1**, `random_seed` = **42**

**Nhanh (demo):**
- `draws` = **500**, `tune` = **500**, `chains` = **1**
    """))

    mode_dd = widgets.Dropdown(
        options=[("Khuyến nghị (chuẩn báo cáo)", "rec"), ("Nhanh (demo)", "demo")],
        value="rec", description="Chế độ"
    )

    prior_beta = widgets.FloatLogSlider(base=10, min=-1, max=2, step=0.1, value=10.0,
                                        description="prior_sigma_beta")
    prior_intc = widgets.FloatLogSlider(base=10, min=-1, max=2, step=0.1, value=10.0,
                                        description="prior_sigma_intercept")
    draws = widgets.IntSlider(min=200, max=3000, step=50, value=1000, description="draws")
    tune  = widgets.IntSlider(min=200, max=3000, step=50, value=1000, description="tune")
    targ  = widgets.FloatSlider(min=0.80, max=0.98, step=0.01, value=0.90, description="target_accept")
    chains = widgets.IntSlider(min=1, max=4, step=1, value=2, description="chains")
    cores  = widgets.IntSlider(min=1, max=2, step=1, value=1, description="cores")
    seed   = widgets.IntText(value=42, description="random_seed")

    def on_mode_change(change):
        if change["new"] == "demo":
            draws.value, tune.value, chains.value = 500, 500, 1
        else:
            draws.value, tune.value, chains.value = 1000, 1000, 2

    mode_dd.observe(on_mode_change, names="value")

    confirm = widgets.Button(description="✅ Xác nhận thông số", button_style="success")
    out = widgets.Output()

    def on_confirm(_):
        with out:
            out.clear_output()
            global BAYES_CFG
            BAYES_CFG = {
                "prior_sigma_beta": float(max(0.1, min(prior_beta.value, 100.0))),
                "prior_sigma_intercept": float(max(0.1, min(prior_intc.value, 100.0))),
                "draws": int(max(200, min(draws.value, 3000))),
                "tune": int(max(200, min(tune.value, 3000))),
                "target_accept": float(max(0.80, min(targ.value, 0.98))),
                "chains": int(max(1, min(chains.value, 4))),
                "cores": int(max(1, min(cores.value, 2))),
                "random_seed": int(seed.value),
            }
            print("ĐÃ CHỌN THÔNG SỐ BAYESIAN:")
            for k, v in BAYES_CFG.items():
                print(f" - {k}: {v}")
            print("\n👉 Chạy **Cell 5C** để huấn luyện & đánh giá Bayesian.")

    confirm.on_click(on_confirm)

    display(widgets.VBox([
        mode_dd,
        prior_beta, prior_intc,
        draws, tune, targ,
        chains, cores, seed,
        confirm, out
    ]))

except Exception:
    print("⚠️ ipywidgets chưa sẵn. Dùng cấu hình khuyến nghị bên dưới, có thể chỉnh số nếu muốn.")
    BAYES_CFG = {
        "prior_sigma_beta": 10.0,
        "prior_sigma_intercept": 10.0,
        "draws": 1000,
        "tune": 1000,
        "target_accept": 0.90,
        "chains": 2,
        "cores": 1,
        "random_seed": 42,
    }
    print("BAYES_CFG =", BAYES_CFG)
    print("👉 Chạy **Cell 5C** để huấn luyện & đánh giá Bayesian.")

# CELL 5C — Huấn luyện Bayesian Logistic theo BAYES_CFG, đánh giá & kết luận

import pymc as pm, arviz as az
import numpy as np, pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

assert "BAYES_CFG" in globals(), "Chưa có BAYES_CFG. Hãy chạy Cell 5B và bấm 'Xác nhận tham số'."

with pm.Model() as bayes_logit:
    beta = pm.Normal("beta", mu=0, sigma=BAYES_CFG["prior_sigma_beta"], shape=Xt_train.shape[1])
    intercept = pm.Normal("intercept", mu=0, sigma=BAYES_CFG["prior_sigma_intercept"])
    logits = intercept + pm.math.dot(Xt_train, beta)
    p = pm.math.sigmoid(logits)
    y_obs = pm.Bernoulli("y_obs", p=p, observed=y_train.values)

    idata = pm.sample(
        draws=BAYES_CFG["draws"], tune=BAYES_CFG["tune"],
        target_accept=BAYES_CFG["target_accept"],
        chains=BAYES_CFG["chains"], cores=BAYES_CFG["cores"],
        random_seed=BAYES_CFG["random_seed"],
        progressbar=True
    )

print("✅ Bayesian model fitted.")
summary = az.summary(idata, var_names=["beta","intercept"], round_to=3)
display(summary.head())

# Posterior mean → dự đoán test
beta_mean = idata.posterior["beta"].mean(dim=("chain","draw")).values
intercept_mean = idata.posterior["intercept"].mean(dim=("chain","draw")).values
logits_test = intercept_mean + Xt_test @ beta_mean
proba_bayes = 1/(1+np.exp(-logits_test))
y_pred_bayes = (proba_bayes >= 0.5).astype(int)

# Đánh giá
acc_b  = accuracy_score(y_test, y_pred_bayes)
prec_b = precision_score(y_test, y_pred_bayes, zero_division=0)
rec_b  = recall_score(y_test, y_pred_bayes, zero_division=0)
f1_b   = f1_score(y_test, y_pred_bayes, zero_division=0)
auc_b  = roc_auc_score(y_test, proba_bayes)

print("\n📊 ĐÁNH GIÁ (Bayesian Logistic)")
print(f"- Accuracy  : {acc_b:.3f}")
print(f"- Precision : {prec_b:.3f}")
print(f"- Recall    : {rec_b:.3f}")
print(f"- F1-score  : {f1_b:.3f}")
print(f"- ROC AUC   : {auc_b:.3f}")

# Top 5 dương/âm theo posterior mean
coef_df_b = pd.DataFrame({"feature": feature_names, "coef": beta_mean})
top_pos_b = coef_df_b.sort_values("coef", ascending=False).head(5)[["feature","coef"]]
top_neg_b = coef_df_b.sort_values("coef", ascending=True).head(5)[["feature","coef"]]

print("\n📈 Top 5 biến DƯƠNG (Bayesian):")
display(top_pos_b)
print("\n📉 Top 5 biến ÂM (Bayesian):")
display(top_neg_b)

# Kết luận bằng lời
pos_list = top_pos_b["feature"].tolist()
neg_list = top_neg_b["feature"].tolist()

print("\n🧭 KẾT LUẬN (Bayesian)")
if selected_threshold is not None:
    print(f"- Target 'Score' ban đầu liên tục → đã chọn ngưỡng = {selected_threshold:.4f} (classification-oriented balance).")
else:
    print("- Target 'Score' đã nhị phân sẵn, không threshold.")

print(f"- Hiệu suất: Accuracy={acc_b:.3f}, Precision={prec_b:.3f}, Recall={rec_b:.3f}, F1={f1_b:.3f}, AUC={auc_b:.3f}")
if pos_list: print(f"- Biến **dương** (tăng xác suất lớp '1'): {', '.join(pos_list)}.")
if neg_list: print(f"- Biến **âm** (giảm xác suất lớp '1'): {', '.join(neg_list)}.")
print("\n💡 Ưu điểm Bayesian: có posterior & credible intervals (xem bảng summary) để đánh giá mức độ chắc chắn của từng biến.")

# CELL 5D — Diễn giải Bayesian bằng % và nhóm biến (chắc chắn dương/âm/không xác định)

import numpy as np
import pandas as pd
import arviz as az
from IPython.display import display

# Kiểm tra dữ liệu cần thiết
assert "idata" in globals(), "❌ Chưa có 'idata'. Hãy chạy Cell 5C trước."
assert "feature_names" in globals(), "❌ Thiếu 'feature_names'. Hãy chắc đã chạy 5A/5C."

# Lấy mẫu posterior của beta: shape (chains, draws, K) → (samples, K)
beta_draws = idata.posterior["beta"].values  # dims: (chain, draw, K)
chains, draws, K = beta_draws.shape
beta_samples = beta_draws.reshape(chains * draws, K)

# Tính thống kê cho từng feature
means = beta_samples.mean(axis=0)
sds   = beta_samples.std(axis=0)
ci_l  = np.quantile(beta_samples, 0.025, axis=0)
ci_u  = np.quantile(beta_samples, 0.975, axis=0)

# Xác suất dấu
p_pos = (beta_samples > 0).mean(axis=0)  # P(beta > 0)
p_neg = 1.0 - p_pos

df_bayes = pd.DataFrame({
    "feature": feature_names,
    "mean": means,
    "sd": sds,
    "ci_2.5%": ci_l,
    "ci_97.5%": ci_u,
    "P(beta>0)": p_pos,
    "P(beta<0)": p_neg
})

# Phân loại theo “độ chắc chắn”
# - Chắc chắn dương: CI thấp > 0 hoặc P(beta>0) >= 0.975
# - Chắc chắn âm   : CI cao  < 0 hoặc P(beta<0) >= 0.975
# - Không xác định : còn lại (CI cắt 0), ưu tiên P(beta>0) ~ 0.5
certain_pos_mask = (df_bayes["ci_2.5%"] > 0) | (df_bayes["P(beta>0)"] >= 0.975)
certain_neg_mask = (df_bayes["ci_97.5%"] < 0) | (df_bayes["P(beta<0)"] >= 0.975)
uncertain_mask   = ~(certain_pos_mask | certain_neg_mask)

df_bayes["category"] = np.where(
    certain_pos_mask, "certain_positive",
    np.where(certain_neg_mask, "certain_negative", "uncertain")
)

# Sắp xếp để lấy top
# - Dương/Âm: theo |mean| giảm dần (tác động mạnh hơn)
# - Không xác định: theo |P(beta>0) - 0.5| tăng dần (gần 50% → mơ hồ hơn)
top_pos = (df_bayes[df_bayes["category"] == "certain_positive"]
           .sort_values("mean", ascending=False)
           .head(5))
top_neg = (df_bayes[df_bayes["category"] == "certain_negative"]
           .sort_values("mean", ascending=True)
           .head(5))
uncertain_sorted = (df_bayes[df_bayes["category"] == "uncertain"]
                    .assign(uncert_score=(df_bayes["P(beta>0)"] - 0.5).abs())
                    .sort_values("uncert_score", ascending=True)
                    .head(5))

# Bảng phần trăm gọn gàng
def fmt_pct(x): return f"{x*100:,.1f}%"
view_cols = ["feature", "mean", "sd", "ci_2.5%", "ci_97.5%", "P(beta>0)", "P(beta<0)"]

print("📊 BẢNG TÓM TẮT POSTERIOR (một phần, top theo |mean|):")
display(df_bayes.reindex(df_bayes["mean"].abs().sort_values(ascending=False).index)
        [view_cols].head(12)
        .assign(**{"P(beta>0)": df_bayes["P(beta>0)"].head(12).map(fmt_pct),
                   "P(beta<0)": df_bayes["P(beta<0)"].head(12).map(fmt_pct)}))

print("\n✅ Top biến **chắc chắn DƯƠNG** (CI95% > 0 hoặc P(β>0)≥97.5%):")
if len(top_pos):
    display(top_pos[view_cols].assign(**{
        "P(beta>0)": top_pos["P(beta>0)"].map(fmt_pct),
        "P(beta<0)": top_pos["P(beta<0)"].map(fmt_pct)
    }))
else:
    print("(không đủ biến thỏa điều kiện)")

print("\n✅ Top biến **chắc chắn ÂM** (CI95% < 0 hoặc P(β<0)≥97.5%):")
if len(top_neg):
    display(top_neg[view_cols].assign(**{
        "P(beta>0)": top_neg["P(beta>0)"].map(fmt_pct),
        "P(beta<0)": top_neg["P(beta<0)"].map(fmt_pct)
    }))
else:
    print("(không đủ biến thỏa điều kiện)")

print("\n⚖️ Top biến **KHÔNG XÁC ĐỊNH** (CI cắt 0, P(β>0) gần 50%):")
if len(uncertain_sorted):
    display(uncertain_sorted[view_cols].assign(**{
        "P(beta>0)": uncertain_sorted["P(beta>0)"].map(fmt_pct),
        "P(beta<0)": uncertain_sorted["P(beta<0)"].map(fmt_pct)
    }))
else:
    print("(không đủ biến thuộc nhóm mơ hồ)")

# Kết luận ngắn gọn bằng lời
pos_names = ", ".join(top_pos["feature"].tolist()[:5]) if len(top_pos) else "không có"
neg_names = ", ".join(top_neg["feature"].tolist()[:5]) if len(top_neg) else "không có"
unc_names = ", ".join(uncertain_sorted["feature"].tolist()[:5]) if len(uncertain_sorted) else "không có"

print("\n🧭 KẾT LUẬN (Bayesian – theo posterior 95% & xác suất dấu)")
if selected_threshold is not None:
    print(f"- Target 'Score' ban đầu liên tục → ngưỡng = {selected_threshold:.4f} (classification balance).")
else:
    print("- Target 'Score' đã nhị phân, không cần threshold.")
print(f"- Biến **chắc chắn dương**: {pos_names}.")
print(f"- Biến **chắc chắn âm**: {neg_names}.")
print(f"- Biến **chưa rõ (mơ hồ)**: {unc_names}.")
print("💡 Diễn giải: với biến chắc chắn dương/âm, credible interval 95% không cắt 0 (hoặc xác suất dấu ≥ 97.5%),\n"
      "còn nhóm mơ hồ có xác suất dấu ~50%, cần thêm dữ liệu hoặc mô hình khác để khẳng định.")